version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout

      # Restore cache from last test run
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: "Install dependencies"
          command: yarn

      # Save cache for a future test run
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Run tests"
          command: yarn test-ci

  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - setup_remote_docker

      # Build docker container for backstroke server
      - run:
          name: Build container image
          command: 'docker build -t backstroke/server:latest .'
      - run:
          name: Login to Docker Hub
          command: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
      - run:
          name: Push container image
          command: 'docker push backstroke/server:latest'

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
